# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Configure sysctl limits
      run: |
       sudo swapoff -a
       sudo sysctl -w vm.swappiness=1
       sudo sysctl -w fs.file-max=262144
       sudo sysctl -w vm.max_map_count=262144


    - name: Run Elasticsearch
      uses: JonasGe/elasticsearch-with-plugins-action@0.1.4
      with:
       elasticsearch version: '8.13.4'
       host port: 9200
       container port: 9200
       host node port: 9300
       node port: 9300
       discovery type: 'single-node'
      env:
        STACK_VERSION: '8.13.4'
            

    - name: Build
      run: dotnet build --no-restore

    - name: Build with warnings
      run: dotnet build /p:TreatWarningsAsErrors=true /consoleloggerparameters:NoSummary

    - name: Test
      run: dotnet test --no-build --verbosity normal --warnaserror
